### ISSUE TITLE
Web Socket connections are not stable

### ISSUE THREAD

**Issue by w01fgang** [nathan-alden/proxy#2]
Sometimes I have next error:
```
2019-06-07 15:36:10 [Error] [DS 9] 127.0.0.1 Unexpected error
System.NotSupportedException: Stream does not support reading.
   at System.IO.BufferedStream.EnsureCanRead()
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at NathanAlden.Proxy.Tcp.TcpClientWrapper.Read() in C:\Users\xxx\Documents\source\proxy\src\Proxy\Tcp\TcpClientWrapper.cs:line 38
   at NathanAlden.Proxy.HttpClient.HttpClient.Read() in C:\Users\xxx\Documents\source\proxy\src\Proxy\HttpClient\HttpClient.cs:line 150
   at NathanAlden.Proxy.Services.DownstreamClientService.DownstreamClient.<>c__DisplayClass19_0.<Run>b__9() in C:\Users\xxx\Documents\source\proxy\src\Proxy\Services\DownstreamClientService\DownstreamClient.cs:line 291
```
Web sockets connection fails but not always, only first few attempts.

**Comment by nathan-alden-sr** [comment]
Sorry, I haven't been very active lately on GitHub. If I can find some time I'll take a look at this. Do you know of a good site I can test websockets with? I hadn't thought of those when I first wrote this.

**Comment by w01fgang** [comment]
There is a websocket connection to get realtime messages from Twitter on Socket.io website https://socket.io/
Thank you!
